apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: syncserverr
  name: syncserverr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: syncserverr
    spec:
      containers:
      - env:
        - name: MONGO_CONNECTION_URL
          value: mongodb://mongodb:27017/sync
        - name: REDIS_CONNECTION_URL
          value: redis://redis:6379
        image: chargetrackserver
        imagePullPolicy: IfNotPresent
        name: syncserverr
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
