apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
      - image: chargetrackclient
        imagePullPolicy: IfNotPresent
        name: webserver
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
